"""Add credentials table

Revision ID: 0
Revises: None
Create Date: 2017-05-15 12:57:41.670553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'credentials',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user', sa.String(), nullable=False),
        sa.Column('username', sa.String(), nullable=False),
        sa.Column('password', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user'),
        sa.UniqueConstraint('username'))
    op.create_index(
        'credentials_user_idx', 'credentials', ['user'], unique=True)
    op.create_index(
        'credentials_username_idx', 'credentials', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('credentials_username_idx', table_name='credentials')
    op.drop_index('credentials_user_idx', table_name='credentials')
    op.drop_table('credentials')
    # ### end Alembic commands ###
